#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

./src/Allclean

wclean ./applications/utilities/preProcessing/FPVToFoam
wclean ./applications/utilities/postProcessing/FPVFoamPost
wclean ./applications/solver/FPVFoam

# ----------------------------------------------------------------- end-of-file
